name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]    
  workflow_dispatch:

jobs:
  validation:
    uses: microsoft/action-python/.github/workflows/validation.yml@0.2.0
    uses: actions/setup-python@v4
    with:
      python-version: "3.9"    

  publish:
    uses: microsoft/action-python/.github/workflows/publish.yml@0.2.0
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
